### ISSUE TITLE
Malfunctioning on 32-bit systems and inconsistent type handling 

### ISSUE THREAD

**Issue by kimikage** [GunnarFarneback/Inflate.jl#16]
Bit sequences should be treated as `Unsigned`, but this program makes heavy use of `Int`. 
As a result, this package does not work on 32-bit systems.
Also, although it works on 64-bit systems, the type handling is inconsistent.

Is this package still maintained?　In other words, is it worth sending a PR?

**Comment by GunnarFarneback** [comment]
Yes, it is. If 32-bit can be run in CI it would improve the chances that it keeps working.

**Comment by kimikage** [comment]
Fixed by #21
