### ISSUE TITLE
Please tag a release?

### ISSUE THREAD

**Issue by sbromberger** [GunnarFarneback/Inflate.jl#2]
Hi,

I've integrated this into LightGraphs and it's working really well! Could you please tag a release so I can put it into `REQUIRE`?

Thank you!

**Comment by GunnarFarneback** [comment]
I want to get travis and attobot set up first. Shouldn't be difficult but I need to read up on it as I've never done it before.

**Comment by sbromberger** [comment]
I'll make a PR with a travis config.

**Comment by GunnarFarneback** [comment]
Thanks and done. Waiting for https://github.com/JuliaLang/METADATA.jl/pull/18055 to get accepted now.
