### ISSUE TITLE
Naming of functions and streams

### ISSUE THREAD

**Issue by GunnarFarneback** [GunnarFarneback/Inflate.jl#4]
The user facing functions `inflate`, `decompress`, and `gunzip` got their names in the gist from 2013 and weren't all that well thought through, at least `decompress` is kind of random. When looking at this again, I think CodecZlib has the better idea to involve the names of the wrapper formats Zlib and Gzip more directly. A way to make the naming more consistent could be:

| Old name | New name |
| ------------- | -------------- |
| `inflate` | `inflate` |
| `decompress` | `inflate_zlib` |
| `gunzip` | `inflate_gzip` |
| `InflateStream` | `InflateStream` |
| `DecompressStream` | `InflateZlibStream` |
| `GunzipStream` | `InflateGzipStream` |

**Comment by sbromberger** [comment]
I don't know about the streams, but I like the idea of overloading `inflate`:
```
abstract type InflateAlg end
struct Alg_gzip <: InflateAlg end
struct Alg_zlib <: InflateAlg end

function inflate(source::Vector{UInt8}, ::Alg_gzip) # code for gzip
...
function inflate(source::Vector{UInt8}, ::Alg_zlib) # code for zlib
...
inflate(source::Vector{UInt8}) = inflate(source, Alg_gzip()) #default
```

**Comment by GunnarFarneback** [comment]
Yes, I've been thinking along those lines too but haven't managed to convince myself that I like it better. One reason is that the optional argument `headers` only makes sense for Gzip and I'm planning to add an option to disable checksum verification, which is meaningless for plain Deflate data. Streams could be handled as parametrized types, but the same objections apply.
