### ISSUE TITLE
Can you add LZW as well?

### ISSUE THREAD

**Issue by sambitdash** [GunnarFarneback/Inflate.jl#7]
@GunnarFarneback 

I have an implementation in the package PDFIO.jl. If you are ok with it, will love to add it to this library to be maintained as part of one class of LZ decompressions. 

Code can be seen here: https://github.com/sambitdash/PDFIO.jl/blob/master/src/Inflate.jl

regards,

Sambit

**Comment by GunnarFarneback** [comment]
I'm sorry about leaving this unanswered indefinitely. I started looking at LZW but other things got in the way until it was forgotten. At this point I prefer to keep the focus on the DEFLATE algorithm.
